apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: certmanager
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-08-01T15:35:11Z"
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: certmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.11.1
    helm.sh/chart: cert-manager-v1.11.1
  name: certmanager-cert-manager
  namespace: default
  resourceVersion: "16024269"
  uid: eaeba140-918d-49fb-9996-84b93259bf26
spec:
  clusterIP: 172.20.30.112
  clusterIPs:
  - 172.20.30.112
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-prometheus-servicemonitor
    port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: certmanager
    app.kubernetes.io/name: cert-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
