apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: starburst
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-27T21:10:24Z"
  labels:
    app: starburst-enterprise
    app.kubernetes.io/managed-by: Helm
    helm-chart: starburst-enterprise-423.1.0
    helm-release: starburst
    managed-by: Helm
    role: prometheus-worker
  name: prometheus-worker-starburst
  namespace: default
  resourceVersion: "41210880"
  uid: 75a8dd1a-7b71-46ce-8d57-fa31d996fc7f
spec:
  clusterIP: 172.20.243.218
  clusterIPs:
  - 172.20.243.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: starburst-enterprise
    helm-chart: starburst-enterprise-423.1.0
    helm-release: starburst
    managed-by: Helm
    role: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
