apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/datasources: de094e6aae7f23a95b19c9bcbefb54045942a73a752346280bd01f6dc142d935
    checksum/extra-secret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    checksum/init-file: 103a292a332246d2311b25b30e290d61b4e023c10bdfa168b580e96e50d012f7
    checksum/init-file-scripts: f7438e33138df2598cecb2202f54c81925df4e11539c493e8a6b5b12d1b0eff6
    checksum/registry-secret: 54e6f6b2e4cba7dbf9893ff249254bbae44c3d2a716bcc3b53ff61e85b14e57b
  creationTimestamp: "2023-12-04T22:00:27Z"
  generateName: ranger-7855c458d8-
  labels:
    app: starburst-ranger
    helm-chart: starburst-ranger-411.0.0
    helm-release: ranger
    managed-by: Helm
    pod-template-hash: 7855c458d8
  name: ranger-7855c458d8-dqqbr
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ranger-7855c458d8
    uid: ba69b9da-bb7c-4747-a441-4ea36c15c713
  resourceVersion: "42728538"
  uid: 3c8567b4-8dff-4b92-918e-ebce017bfaef
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: apps
            operator: In
            values:
            - base
  containers:
  - args:
    - /init/initFile
    - ranger-admin
    command:
    - /bin/bash
    env:
    - name: RANGER__policymgr_port
      value: "6080"
    - name: RANGER__db_name
      value: eks_ranger
    - name: RANGER__db_root_user
      value: postgres
    - name: RANGER__db_root_password
      valueFrom:
        secretKeyRef:
          key: databaseRootPassword
          name: ranger-database-password
    - name: RANGER__db_user
      value: postgres
    - name: RANGER__db_password
      valueFrom:
        secretKeyRef:
          key: databasePassword
          name: ranger-database-password
    - name: RANGER__db_host
      value: johndee-burks-bootcamp-postgresql.cs8j7iukogcy.us-east-2.rds.amazonaws.com
    - name: WAIT_FOR
      value: johndee-burks-bootcamp-postgresql.cs8j7iukogcy.us-east-2.rds.amazonaws.com:5432
    - name: RANGER__rangerAdmin_password
      valueFrom:
        secretKeyRef:
          key: admin.passwords.admin
          name: ranger-password-secret
    - name: RANGER__rangerTagsync_password
      valueFrom:
        secretKeyRef:
          key: admin.passwords.tagsync
          name: ranger-password-secret
    - name: RANGER__rangerUsersync_password
      valueFrom:
        secretKeyRef:
          key: admin.passwords.usersync
          name: ranger-password-secret
    - name: RANGER__keyadmin_password
      valueFrom:
        secretKeyRef:
          key: admin.passwords.keyadmin
          name: ranger-password-secret
    - name: WAIT_TIMEOUT
      value: "15"
    image: harbor.starburstdata.net/starburstdata/starburst-ranger-admin:2.3.0-e.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: ranger-admin
    ports:
    - containerPort: 6080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    startupProbe:
      exec:
        command:
        - sh
        - -c
        - grep 'ranger-admin started' /opt/ranger/starburst-ranger-server-admin-*/ews/logs/start.sh.log
      failureThreshold: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /init
      name: init-file
      readOnly: true
    - mountPath: /scripts
      name: scripts-volume
    - mountPath: /config
      name: datasources-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4gc7d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: registry-secret-ranger-starburst-ranger
  nodeName: ip-10-0-189-79.us-east-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: init-file
    secret:
      defaultMode: 420
      secretName: init-secret-ranger-starburst-ranger
  - configMap:
      defaultMode: 493
      name: scripts-configmap
    name: scripts-volume
  - name: datasources-volume
    secret:
      defaultMode: 420
      secretName: datasources-secret-ranger-starburst-ranger
  - name: kube-api-access-4gc7d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-04T22:02:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-04T22:04:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-04T22:04:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-04T22:02:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ddd57338c27e533a625f3a6054fda99ae3e4c93c72630ef302d147f682e5c27e
    image: harbor.starburstdata.net/starburstdata/starburst-ranger-admin:2.3.0-e.5
    imageID: harbor.starburstdata.net/starburstdata/starburst-ranger-admin@sha256:eb55c150eecf4330a68a260dddb24333d2b2ce1e6119a0368f060087eaab73c9
    lastState: {}
    name: ranger-admin
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-04T22:03:12Z"
  hostIP: 10.0.189.79
  phase: Running
  podIP: 10.0.178.47
  podIPs:
  - ip: 10.0.178.47
  qosClass: Burstable
  startTime: "2023-12-04T22:02:21Z"
