apiVersion: v1
data:
  adl.oauth2.credential: ""
  awsS3.secretKey: ""
  azure.abfs.accessKey.accessKey: ""
  azure.abfs.oauth.secret: ""
  azure.wasb.accessKey: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: hive
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-05-16T05:12:00Z"
  labels:
    app: starburst-hive
    app.kubernetes.io/managed-by: Helm
    helm-chart: starburst-hive-411.0.0
    helm-release: hive
    managed-by: Helm
  name: hive-object-storage-secret
  namespace: default
  resourceVersion: "506798"
  uid: 3954ea8b-856e-4e9a-8699-11c16476e290
type: Opaque
