apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-12-05T19:11:37Z"
  generateName: certmanager-cert-manager-cainjector-558bf5b55d-
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: certmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: v1.11.1
    helm.sh/chart: cert-manager-v1.11.1
    pod-template-hash: 558bf5b55d
  name: certmanager-cert-manager-cainjector-558bf5b55d-xmhm8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: certmanager-cert-manager-cainjector-558bf5b55d
    uid: 549ae86d-b05f-41d9-9258-8ac3ce0bc1ab
  resourceVersion: "42915413"
  uid: 2830152a-d3eb-4ca5-b581-039d8970e66c
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: apps
            operator: In
            values:
            - base
  containers:
  - args:
    - --v=2
    - --leader-election-namespace=kube-system
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/jetstack/cert-manager-cainjector:v1.11.1
    imagePullPolicy: IfNotPresent
    name: cert-manager-cainjector
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t78mk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-183-212.us-east-2.compute.internal
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: certmanager-cert-manager-cainjector
  serviceAccountName: certmanager-cert-manager-cainjector
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-t78mk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-05T19:11:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-05T19:11:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-05T19:11:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-05T19:11:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://558dc45424d2adbd836fed6858e195aa921925683cb4d2ff3905763717e07015
    image: quay.io/jetstack/cert-manager-cainjector:v1.11.1
    imageID: quay.io/jetstack/cert-manager-cainjector@sha256:db61438c42ee2bcbde6a1243a1319cb01d22b904b6e4f1cd6d0e879befbc0e49
    lastState: {}
    name: cert-manager-cainjector
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-05T19:11:43Z"
  hostIP: 10.0.183.212
  phase: Running
  podIP: 10.0.179.139
  podIPs:
  - ip: 10.0.179.139
  qosClass: BestEffort
  startTime: "2023-12-05T19:11:37Z"
