apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: certmanager
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-08-01T15:35:11Z"
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: certmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.11.1
    helm.sh/chart: cert-manager-v1.11.1
  name: certmanager-cert-manager-webhook
  namespace: default
  resourceVersion: "16024231"
  uid: 4c8acef7-5a7e-4872-be0b-1afa4fd5cd75
